### ISSUE TITLE
[Question] How do you teleport to the RED/s?

### ISSUE THREAD

**Issue by NurdTurd** [cyberpwnn/React#2]
I would just like to know how I can teleport to where the redstone is taking place.
Thanks. 👍

**Comment by cyberpwnn** [comment]
Click it :P

**Comment by NurdTurd** [comment]
How though? When I execute `/re mon` I see the monitor and I can scroll but where do I click ?
Is this only a `/re status` feature ?
Like, does the redstone get logged into the book and then I can click the TP text in the book ?

**Comment by cyberpwnn** [comment]
If the server is lagging because of redstone it will send a message such as 

Redstone Overload: Stabilizing... at [31, -12]

Click the coords and it will tell you, however if i were to track all of the redstone, it would cause more lag that it would help. You can only teleport with those messages at the moment.

**Comment by NurdTurd** [comment]
Ahh, I see. I get it now. Thanks!
